In [1]:
import sys
sys.path.append('..')

from virtuous.GenerationModel import GenerationModel
from virtuous.FinancialModel import FinancialModel

In [2]:
start_year = 2022         # year the power plant was built
investigate_year = 2026   # year we are simulating for

In [3]:
""" simulate energy generation """
generation = GenerationModel(
    start_year=start_year,
    peak_energy=100 * 0.2 * (30 * 24), # 100MW * capacity_factor=0.2 and hours per month
    seasonality=0.5,
    degradation=0.05/12, # 5% per year
    uncertainty=0.1,
    )
monthly_data = generation.calculate_year(investigate_year)
# monthly_data

In [4]:
""" calculate costs and revenues for this energy """
financial = FinancialModel(
    start_year=start_year,
    energy_price=25,
    cleaning_cost=30000,
    maintenance_cost=40000,
    )
monthly_data = financial.extend_with_financial(
    monthly_data=monthly_data,
    year=investigate_year)
monthly_data

                  energy  cleaning_cost  maintenance_cost        revenue
date
2026-01-31   5609.013247         -30000            -40000  140225.331184
2026-02-28   5625.564584              0                 0  140639.114590
2026-03-31   7409.228869              0                 0  185230.721719
2026-04-30   8675.267963              0                 0  216881.699083
2026-05-31   9685.874066              0                 0  242146.851659
2026-06-30  10324.549990              0                 0  258113.749753
2026-07-31  12166.054429         -30000                 0  304151.360718
2026-08-31  11622.404635              0                 0  290560.115865
2026-09-30  10533.381883              0                 0  263334.547076
2026-10-31   8222.911632              0                 0  205572.790791
2026-11-30   7403.270120              0                 0  185081.752995
2026-12-31   6006.788639              0                 0  150169.715965

In [5]:
# ... implement the visualization here ...