In [32]:
import sys
sys.path.append('..')

from virtuous.GenerationModel import GenerationModel
from virtuous.FinancialModel import FinancialModel

In [33]:
start_year = 2022         # year the power plant was built
investigate_year = 2042   # year we are simulating for

In [34]:
""" simulate energy generation """
generation = GenerationModel(
    start_year=start_year,
    peak_energy=100 * 0.2 * (30 * 24), # 100MW * capacity_factor=0.2 and hours per month
    seasonality=0.5,
    degradation=0.02/12, # 2% per year
    uncertainty=0.1,
    )
monthly_data = generation.calculate_year(investigate_year)
# monthly_data

In [35]:
""" calculate costs and revenues for this energy """
financial = FinancialModel(
    start_year=start_year,
    energy_price=25,
    cleaning_cost=30000,
    maintenance_cost=40000,
    )
monthly_data = financial.extend_with_financial(
    monthly_data=monthly_data,
    year=investigate_year)
monthly_data

                 energy  cleaning_cost  maintenance_cost        revenue
date
2042-01-31  4650.682592         -30000            -40000  116267.064796
2042-02-28  5017.142134              0                 0  125428.553351
2042-03-31  5463.352741              0                 0  136583.818529
2042-04-30  6744.915413              0                 0  168622.885321
2042-05-31  7046.303940              0                 0  176157.598488
2042-06-30  7740.715355              0                 0  193517.883864
2042-07-31  8705.132577         -30000                 0  217628.314416
2042-08-31  8881.935052              0                 0  222048.376306
2042-09-30  6797.131723              0                 0  169928.293067
2042-10-31  6174.075102              0                 0  154351.877547
2042-11-30  5278.931311              0                 0  131973.282784
2042-12-31  4249.177932              0                 0  106229.448296

In [36]:
# ... implement the visualization here ...